# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import orchestrator_pb2 as orchestrator__pb2


class DatabrokerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_next = channel.unary_unary(
                '/Databroker/get_next',
                request_serializer=orchestrator__pb2.Empty.SerializeToString,
                response_deserializer=orchestrator__pb2.Features.FromString,
                )


class DatabrokerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_next(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabrokerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_next': grpc.unary_unary_rpc_method_handler(
                    servicer.get_next,
                    request_deserializer=orchestrator__pb2.Empty.FromString,
                    response_serializer=orchestrator__pb2.Features.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Databroker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Databroker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_next(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Databroker/get_next',
            orchestrator__pb2.Empty.SerializeToString,
            orchestrator__pb2.Features.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class PredictionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.predict = channel.unary_unary(
                '/Prediction/predict',
                request_serializer=orchestrator__pb2.Features.SerializeToString,
                response_deserializer=orchestrator__pb2.Predictions.FromString,
                )


class PredictionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'predict': grpc.unary_unary_rpc_method_handler(
                    servicer.predict,
                    request_deserializer=orchestrator__pb2.Features.FromString,
                    response_serializer=orchestrator__pb2.Predictions.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Prediction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Prediction(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Prediction/predict',
            orchestrator__pb2.Features.SerializeToString,
            orchestrator__pb2.Predictions.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
