FROM ubuntu:18.04

RUN apt-get update -y && \
    apt-get install --no-install-recommends -y python3-pip python3-dev && \
    apt clean && rm -rf /var/lib/apt/lists/*
WORKDIR /
COPY ./requirements.txt /requirements.txt
RUN pip3 install --upgrade pip && pip3 install --no-cache-dir -r requirements.txt

RUN useradd -ms /bin/bash admin

COPY ./app /app

RUN chown -R admin:admin ./app
RUN chmod 755 ./app



USER admin

EXPOSE 8063
EXPOSE 8064

COPY license-1.0.0.json visualization.proto visualization_pb2.py visualization_pb2_grpc.py visualization.py run.py ./


ENTRYPOINT [ "python3","-u","visualization.py" ]